- README.md
Signed-off-by: Cameron Shorter <cameron.shorter@gmail.com>
> test update #3

- README.adoc
- adoc-parameters.txt
- concept/tmpl-discussion.adoc
- how-to/tmpl-howto.adoc
- reference/tmpl-logging.adoc
- reference/tmpl-reference.adoc
- tutorials/tmpl-tutorial.adoc
If merged, the changes summarised below will be merged.
- Created folder structure for template types.
- An initial contribution of template types in Asciidoc format.
- `README.adoc` at the project root is a How-To Guide for Templates that I created.
- `adoc-parameters.txt` file is specific to Asciidoc and lets you single-source 
variables across all your docs.
> Asciidoc templates for consideration

- api-quickstart/api-quickstart.md
- how-to/about-howto.md
- how-to/template-howto.adoc
- tutorial/about-tutorial.md
- tutorial/template-tutorial.adoc
**Please do not merge - this wording review is still in progress**
> WIP: Spell all instances of 'prerequisites' correctly and consistently.

- how-to/about-howto.md
Replace: "anything" with "concepts" in the sentence `"Sometimes you need to explain in detail how to do a specific task to a user. You don't need to teach them anything, but you do need to prescribe a set of sequential steps they must do in that order otherwise they won't be able to use a feature properly."`
Closes #84
> docs: update about-howto.md

- api-quickstart/about-quickstart.md
The intented results is a little vague. I think the intended result is for the user to experience your product working, so I tried to word it more that way.
I think the second point now captures what I deleted regarding making the benefits of your product apparent to the user (not just telling them, but showing them).
Attempts to resolve #37
> Made intro section more generic and concise

- writing-tips.md
Fixes #64, #71, and #69 
I've made the relevant changes, as suggested in the issues.
> docs: Update writing-tips.md

- writing-tips.md
adding link to Wikipedia and link to article discussing other grammar linter tools
> linter fix (issue #66)

- how-to/about-howto.md
> rewording: about-howto.md

- logging/template-logging.adoc
> reword "pathing"

- how-to/about-how-to.md
- reference/about-reference.md
- writing-tips.md
@jaredmorgs please review. I can only ask you to review by tagging you as I am not a maintainer.
- Implemented the suggestions in the issues: #70, #44, #87, #72, and #67.
- All this time I added a separate commit for every suggestion. 
- For this PR I cloned the repo on my machine and fixed everything in one go. Is that fine or would you rather I add a separate commit for every issue?
> fix: implement suggestions in #70, #44, #87, #72, #67

- api-quickstart/about-quickstart.md
- api-reference/about-api-reference.md
- reference/about-reference.md
> Replaced links with link texts

- how-to/about-how-to.md
- reference/about-reference.md
- tutorial/about-tutorial.md
Things changed and errors found:
- Fixed: Added a comma to signify a brief pause wherever necessary.
- Fixed: Changed the singularity/plurality of words as per the sentence.
- Fixed: Removed unnecessary word(s) used in the sentence(s).
> Fixed some grammatical errors

- discussion/about-discussion.md
Changes made: 
- Reframed the beginning of discussion article to contain less complicated terms and make it more consistent with the language.
Resolves #40
> Reframed the beginning of discussion article

- discussion/template-discussion.adoc
Addresses: https://github.com/thegooddocsproject/templates/issues/42
> add top level header to discussion

- how-to/template-how-to.md
Closes: https://github.com/thegooddocsproject/templates/issues/54
> add note about other info

- how-to/about-how-to.md
This PR adds more details to Before you Start section of how-to and targets issue #90 .
> Update Before you start

- README.md
> __ALL Pull-Requests require an associated [Issue](https://github.com/thegooddocsproject/templates/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) as documented in [How to contribute](https://github.com/thegooddocsproject/templates/blob/master/contribute.md#contributing).__
closes: https://github.com/thegooddocsproject/templates/issues/77
We added a column to the `readme` with template information
N/A
---
> __Pull-request reviewer__ should ensure the following
> add description column to table in README

- how-to/about-how-to.md
Changes made: 
- Completed the "About the Step-by-step guide section" of `about-how-to.md`
Resolves #92
> Completed the "About Step-by-step guide section"

- how-to/template-how-to.md
Changes made: 
- Added step-4: Optional: Conclusion in the `step-by-step guide` section of template-how-to.md
For issue: #58
> added step-4: Conclusion in the step-by-step guide

- templates-list.md
This PR indicates who is working on which template to the best of my knowledge.
> Update templates list to indicate who is working on them

- quickstarts/about-quickstarts.md
- quickstarts/template-quickstarts.md
> __ALL Pull-Requests require an associated [Issue](https://github.com/thegooddocsproject/templates/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) as documented in [How to contribute](https://github.com/thegooddocsproject/templates/blob/master/CONTRIBUTING.md#contributing).__
This pull request adds a working draft of a quickstart guide and quickstart template to the `dev` branch. 
* Adds a `quickstarts` directory to the `dev` branch
* Adds `about-quickstarts.md` and `quickstarts-template.md` files
I added the draft that I presented during the meeting on Monday. There are a few comments I left in there from our discussion. If needed, I can do a bit more work before passing it off to the AMEA/APAC Group. 
---
> __Pull-request reviewer__ should ensure the following
> Add rough drafts of Deanna's quickstart materials

- quickstarts/template-quickstarts.md
> __ALL Pull-Requests require an associated [Issue](https://github.com/thegooddocsproject/templates/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) as documented in [How to contribute](https://github.com/thegooddocsproject/templates/blob/master/CONTRIBUTING.md#contributing).__
I realized that I forgot to copy the quickstarts template into `template-quickstarts.md`.
Replaces the content in `template-quickstarts.md`
Please make sure the content changed!
---
> __Pull-request reviewer__ should ensure the following
> Add missing quickstart template
